/* Action Types for categories */
export const HANDLE_ERROR_CATEGORIES = 'HANDLE_ERROR_CATEGORIES'
export const RECEIVE_GET_CATEGORIES = 'RECEIVE_GET_CATEGORIES'
export const REQUEST_GET_CATEGORIES = 'REQUEST_GET_CATEGORIES'
export const SELECT_CATEGORY = 'SELECT_CATEGORY'
export const UNSELECT_CATEGORY = 'UNSELECT_CATEGORY'

/* Action Types for posts */
export const DECREASE_COMMENT_COUNT = 'DECREASE_COMMENT_COUNT'
export const HANDLE_ERROR_POSTS = 'HANDLE_ERROR_POSTS'
export const INCREASE_COMMENT_COUNT = 'INCREASE_COMMENT_COUNT'
export const INIT_POST = 'INIT_POST'

export const RECEIVE_ADD_POST = 'RECEIVE_ADD_POST'
export const RECEIVE_DELETE_POST = 'RECEIVE_DELETE_POST'
export const RECEIVE_DOWNVOTE_POST = 'RECEIVE_DOWNVOTE_POST'
export const RECEIVE_GET_POST = 'RECEIVE_GET_POST'
export const RECEIVE_GET_POSTS = 'RECEIVE_GET_POSTS'
export const RECEIVE_UPDATE_POST = 'RECEIVE_UPDATE_POST'
export const RECEIVE_UPVOTE_POST = 'RECEIVE_UPVOTE_POST'

export const REQUEST_ADD_POST = 'REQUEST_ADD_POST'
export const REQUEST_DELETE_POST = 'REQUEST_DELETE_POST'
export const REQUEST_DOWNVOTE_POST = 'REQUEST_DOWNVOTE_POST'
export const REQUEST_GET_POST = 'REQUEST_GET_POST'
export const REQUEST_GET_POSTS = 'REQUEST_GET_POSTS'
export const REQUEST_UPDATE_POST = 'REQUEST_UPDATE_POST'
export const REQUEST_UPVOTE_POST = 'REQUEST_UPVOTE_POST'

export const SELECT_POST = 'SELECT_POST'
export const UNSELECT_POST = 'UNSELECT_POST'

/* Action Types for comments */
export const CLEAR_COMMENTS = 'CLEAR_COMMENTS'
export const HANDLE_ERROR_COMMENTS = 'HANDLE_ERROR_COMMENTS'

export const RECEIVE_ADD_COMMENT = 'RECEIVE_ADD_COMMENT'
export const RECEIVE_DELETE_COMMENT = 'RECEIVE_DELETE_COMMENT'
export const RECEIVE_DOWNVOTE_COMMENT = 'RECEIVE_DOWNVOTE_COMMENT'
export const RECEIVE_GET_COMMENTS = 'RECEIVE_GET_COMMENTS'
export const RECEIVE_UPDATE_COMMENT = 'RECEIVE_UPDATE_COMMENT'
export const RECEIVE_UPVOTE_COMMENT = 'RECEIVE_UPVOTE_COMMENT'

export const REQUEST_ADD_COMMENT = 'REQUEST_ADD_COMMENT'
export const REQUEST_DELETE_COMMENT = 'REQUEST_DELETE_COMMENT'
export const REQUEST_DOWNVOTE_COMMENT = 'REQUEST_DOWNVOTE_COMMENT'
export const REQUEST_GET_COMMENTS = 'REQUEST_GET_COMMENTS'
export const REQUEST_UPDATE_COMMENT = 'REQUEST_UPDATE_COMMENT'
export const REQUEST_UPVOTE_COMMENT = 'REQUEST_UPVOTE_COMMENT'
